### ISSUE TITLE
Error: Txn version not supported

### ISSUE THREAD

**Issue by bee344** [Zondax/ledger-statemine#43]
I'm getting this error while trying to send a tx with ledger Nano X to Asset Hub, both Kusama's and Polkadot's.
Firmware version: 2.2.1
Statemine app version: 11.93960.0

```
? Select Network Kusama Asset Hub
? Select Action Transfer Native
? sending from mnemonic type ledger for ledger ledger
? send to address 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
? Input amount (will be multiplied by decimals) 1
2023-06-30 09:38:05        API/INIT: statemine/9420: Not decorating runtime apis without matching versions: FungiblesApi/2 (1 known)
{
  args: [ '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty', 1000000000000 ]
}
sending ledger transaction
{
  sender: {
    address: 'FKbiKKAQ9bAUYrPuFFAS9rRutrYWMzXrgUgeY9DCUSy3rRt',
    publicKey: '0x797a89ab948861184690b78574d21cdeb46d6bb9691f04266468318b421483a6'
  }
}
{
  payload: {
    specVersion: '0x000024cc',
    transactionVersion: '0x0000000d',
    address: 'FKbiKKAQ9bAUYrPuFFAS9rRutrYWMzXrgUgeY9DCUSy3rRt',
    blockHash: '0xed5fd4d1798d15f4c6c6b502f61eba88a3d751b55378f7850c3adf9d16ea9748',
    blockNumber: '0x004974de',
    era: '0xe401',
    genesisHash: '0x48239ef607d7928874027a43a67689209727dfb3d3dc5e5b03a39bdc2eda771a',
    method: '0x0a07008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48070010a5d4e8',
    nonce: '0x00000000',
    signedExtensions: [
      'CheckNonZeroSender',
      'CheckSpecVersion',
      'CheckTxVersion',
      'CheckGenesis',
      'CheckMortality',
      'CheckNonce',
      'CheckWeight',
      'ChargeAssetTxPayment'
    ],
    tip: '0x00000000000000000000000000000000',
    version: 4
  }
}
/home/bee344/Documentos/parity/asset_cli_tool/node_modules/@polkadot/hw-ledger/cjs/bundle.js:15
        throw new Error(result.error_message);
              ^
Error: Txn version not supported
    at wrapError (/home/bee344/Documentos/parity/asset_cli_tool/node_modules/@polkadot/hw-ledger/cjs/bundle.js:15:15)
    at async /home/bee344/Documentos/parity/asset_cli_tool/node_modules/@polkadot/hw-ledger/cjs/bundle.js:73:35
    at async Ledger.withApp (/home/bee344/Documentos/parity/asset_cli_tool/node_modules/@polkadot/hw-ledger/cjs/bundle.js:91:20)
    at async LedgerSigner.signPayload (/home/bee344/Documentos/parity/asset_cli_tool/blockchainServices/setup.ts:73:27)
    at async Submittable.__internal__signViaSigner (/home/bee344/Documentos/parity/asset_cli_tool/node_modules/@polkadot/api/cjs/submittable/createClass.js:113:30)
    at async /home/bee344/Documentos/parity/asset_cli_tool/node_modules/@polkadot/api/cjs/submittable/createClass.js:65:36
error Command failed with exit code 1.
```

**Comment by carlosala** [comment]
We are aware of that, Ledger didn't upgrade the app last time.
We'll keep you posted in this issue.
Sorry for the inconvenience

**Comment by bee344** [comment]
Hi @carlosala thanks for the quick reply! The same thing is happening with the Statemint app, just letting you know.

**Comment by bee344** [comment]
Update: solved with [PR 44](https://github.com/Zondax/ledger-statemine/pull/44)
